name: ðŸª² Bug report
description: Report something that's not working as expected
title: "[BUG] "
labels: [bug]
assignees: [TaffarelJr]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for helping to fix something that's broken! ðŸ¤— See
        [CONTRIBUTING.md](https://github.com/TaffarelJr/test-me/blob/main/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report)
        for tips on writing an effective bug report.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: âœ… Prerequisites
      description: >
        Please check these boxes before submitting a new bug report:
      options:
        - label: >
            I've searched the
            [documentation](https://github.com/TaffarelJr/test-me/tree/main/docs)
            and [Wiki](https://github.com/TaffarelJr/test-me/wiki),
            and I've confirmed this is a bug.
          required: true
        - label: >
            I've searched (or posted in) the
            [Discussions](https://github.com/TaffarelJr/test-me/discussions)
            about this bug.
          required: true
        - label: >
            I've searched the existing
            [Issues](https://github.com/TaffarelJr/test-me/issues)
            and this bug has not been reported yet.
          required: true

  - type: textarea
    id: description
    attributes:
      label: ðŸ“ Description
      description: >
        Give a clear and concise description of the bug:
      placeholder: What's the bug?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: ðŸ” Steps to Reproduce
      description: >
        Include minimal steps to reproduce the bug:
      placeholder: What are the steps to reproduce?
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ðŸŸ¢ Expected Behavior
      description: >
        Describe what you expect to happen:
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ðŸ”´ Actual Behavior
      description: >
        Describe what actually happens instead:
      placeholder: What actually happens?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: ðŸ“¸ Screenshots
      description: >
        Add screenshots to help illustrate the problem, if applicable
        (include text descriptions to help with searching):
      placeholder: Screenshots or visual aids
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: ðŸ’» Environment
      description: >
        Describe the environment in which the bug occurred:
      placeholder: Environment details
      value: |
        - Hardware: [e.g. 8-core CPU, 16GB RAM]
        - Architecture: [e.g. x86, x64, ARM64]
        - OS: [e.g. Windows 11, macOS 15, iOS 18]
        - Browser: [e.g. Chrome, Safari]
        - Platform: [e.g. .NET 9, Node.js 22]
        - Dependency: [e.g. morelinq 4.0.0, eslint 9.20.0]
        - Project version: [e.g. 1.2.3]
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: âž• Additional Context
      description: >
        Add any other context about the bug here
        (insights, potential causes, relevant code, related issues, etc.):
      placeholder: Anything else we should know?
    validations:
      required: false
